### PR TITLE
Update test and add DataScience workflow

### PR DESCRIPTION
**Pull request by ralatsdc**
Tests AisAudioLabeler module using a GitHub workflow.

### CODE REVIEW

**Comment by cglewis** [comment]
@ralatsdc 169k lines for a test JSON file seems pretty excessive - is all of that necessary to run the tests? Similarly, the 4Mb parquet file.

**Comment by ralatsdc** [comment]
Should be all set, Charlie.

**Comment by cglewis** [comment]
@ralatsdc did you see my comment above?

**Comment by ralatsdc** [comment]
Yes, apologies, meant to reply. The number of lines is not really necessary. Of course, the parquet size is set by the number of lines. Shall we reduce now? Or, address later?

**Comment by cglewis** [comment]
Reduce now and rebase so that it's not part of the git history, otherwise every time the repo is cloned the cost in download size is incurred.

**Pull request merged**
